import React, { useState, useEffect, useRef } from 'react';
import API from '../utils/api';
import toast from 'react-hot-toast';
import { consumePendingCustomerTarget, subscribeCustomerTarget } from '../utils/voiceBus';
import { getPageCache, setPageCache } from '../utils/pageCache';
import RefreshButton from '../components/RefreshButton';

const Customers = () => {
  const cachedCustomers = getPageCache('customers');
  const [customers, setCustomers] = useState(cachedCustomers || []);
  const [loading, setLoading] = useState(!cachedCustomers);
  const [refreshing, setRefreshing] = useState(false);
  const [showModal, setShowModal] = useState(false);
  const [editingCustomer, setEditingCustomer] = useState(null);
  const [search, setSearch] = useState('');
  const [filterStatus, setFilterStatus] = useState('all');
  const [filterPayment, setFilterPayment] = useState('all');
  const [sendingWhatsApp, setSendingWhatsApp] = useState(null);
  const [showBulkModal, setShowBulkModal] = useState(false);
  const [bulkDayFilter, setBulkDayFilter] = useState('all'); // 'all' or a billing-day number as a string
  const [bulkSelected, setBulkSelected] = useState({}); // { [customerId]: true }
  const [bulkSending, setBulkSending] = useState(false);
  const [bulkResults, setBulkResults] = useState([]); // links generated by the last send, kept for the individual "Open" fallback
  const [bulkOpenedIds, setBulkOpenedIds] = useState({}); // { [customerId]: true } - which links have been opened so far
  const [showHistoryModal, setShowHistoryModal] = useState(false);
  const [historyCustomer, setHistoryCustomer] = useState(null);
  const [historyLogs, setHistoryLogs] = useState([]);
  const [historyLoading, setHistoryLoading] = useState(false);

  const [formData, setFormData] = useState({
    name: '',
    customerId: '',
    monthlyFee: '',
    pendingDues: '0',
    connectionDate: '',
    phone: '',
    status: 'Active',
    paymentStatus: 'Unpaid',
  });

  const customersRef = useRef([]);

  const matchPendingTarget = (list, target) =>
    list.find(
      (c) =>
        (target.mongoId && c._id === target.mongoId) ||
        (target.customerId && c.customerId === target.customerId)
    );

  useEffect(() => {
    loadCustomers();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    customersRef.current = customers;
  }, [customers]);

  // Handles a voice command like "open Ali" said while ALREADY on this page.
  // Navigating to the same route never remounts it, so the mount effect
  // above (which reads the pending target once via consumePendingCustomerTarget)
  // would otherwise never run again - this is what makes "open <name>" open
  // the profile immediately even when we're already sitting on /customers.
  useEffect(() => {
    const unsubscribe = subscribeCustomerTarget(({ target }) => {
      consumePendingCustomerTarget(); // we're handling it right now, clear it
      const found = matchPendingTarget(customersRef.current, target);
      if (found) {
        openEditModal(found);
      } else {
        // Not in the currently loaded list (e.g. just added elsewhere) -
        // refresh and let loadCustomers' own pending-target check open it.
        loadCustomers();
      }
    });
    return unsubscribe;
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const loadCustomers = async (isManualRefresh = false) => {
    try {
      if (isManualRefresh) setRefreshing(true);
      else if (!cachedCustomers) setLoading(true);
      const res = await API.get('/customers?limit=1000');
      const list = res.data.data;
      setCustomers(list);
      setPageCache('customers', list);

      // If a voice command navigated here wanting a specific customer opened
      // (e.g. "open John's profile"), do that now that we have the list.
      const pending = consumePendingCustomerTarget();
      if (pending) {
        const found = list.find(
          (c) =>
            (pending.target.mongoId && c._id === pending.target.mongoId) ||
            (pending.target.customerId && c.customerId === pending.target.customerId)
        );
        if (found) openEditModal(found);
      }
    } catch (error) {
      toast.error('Failed to load customers');
      console.error('Error:', error);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  const handleInputChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const resetForm = () => {
    setFormData({
      name: '',
      customerId: '',
      monthlyFee: '',
      pendingDues: '0',
      connectionDate: '',
      phone: '',
      status: 'Active',
      paymentStatus: 'Unpaid',
    });
    setEditingCustomer(null);
  };

  const openAddModal = () => {
    resetForm();
    setShowModal(true);
  };

  const openEditModal = (customer) => {
    setEditingCustomer(customer);
    setFormData({
      name: customer.name,
      customerId: customer.customerId,
      monthlyFee: customer.monthlyFee,
      pendingDues: customer.pendingDues || 0,
      connectionDate: customer.connectionDate || '',
      phone: customer.phone || '',
      status: customer.status,
      paymentStatus: customer.paymentStatus,
    });
    setShowModal(true);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      if (editingCustomer) {
        await API.put(`/customers/${editingCustomer._id}`, formData);
        toast.success('Customer updated successfully!');
      } else {
        await API.post('/customers', formData);
        toast.success('Customer added successfully!');
      }
      setShowModal(false);
      resetForm();
      loadCustomers();
    } catch (error) {
      toast.error(error.response?.data?.message || 'Operation failed');
      console.error('Error:', error);
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Are you sure you want to delete this customer?')) return;
    try {
      await API.delete(`/customers/${id}`);
      toast.success('Customer deleted successfully!');
      loadCustomers();
    } catch (error) {
      toast.error('Failed to delete customer');
      console.error('Error:', error);
    }
  };

  // Opens the "who changed what, and when" audit trail for one customer -
  // kept for legal/compliance record-keeping.
  const openHistoryModal = async (customer) => {
    setHistoryCustomer(customer);
    setShowHistoryModal(true);
    setHistoryLoading(true);
    setHistoryLogs([]);
    try {
      const res = await API.get(`/customers/${customer._id}/history`);
      setHistoryLogs(res.data.data || []);
    } catch (error) {
      toast.error('Failed to load change history');
      console.error('Error:', error);
    } finally {
      setHistoryLoading(false);
    }
  };

  const sendWhatsAppReminder = async (customer) => {
    if (!customer.phone || customer.phone.trim() === '') {
      toast.error('No phone number available for this customer!');
      return;
    }

    setSendingWhatsApp(customer._id);
    try {
      const res = await API.post('/whatsapp/send', {
        customerId: customer.customerId
      });

      if (res.data.success) {
        window.open(res.data.data.whatsappUrl, '_blank');
        toast.success(`WhatsApp opened for ${customer.name}!`);
      }
    } catch (error) {
      toast.error(error.response?.data?.message || 'Failed to send reminder');
      console.error('Error:', error);
    } finally {
      setSendingWhatsApp(null);
    }
  };

  // Every Unpaid customer with a phone number - the full pool the Bulk
  // WhatsApp modal draws from before any billing-day filter is applied.
  const unpaidWithPhoneAll = customers.filter((c) => c.paymentStatus === 'Unpaid' && c.phone);

  // How many unpaid+phone customers fall on each billing day, so the
  // dropdown can show e.g. "Day 2 (5 unpaid)" instead of a bare number.
  const bulkDayCounts = {};
  unpaidWithPhoneAll.forEach((c) => {
    const d = parseFloat(c.connectionDate);
    if (!isNaN(d)) bulkDayCounts[d] = (bulkDayCounts[d] || 0) + 1;
  });
  const bulkAvailableDays = Object.keys(bulkDayCounts)
    .map(Number)
    .sort((a, b) => a - b);

  // "all" = every unpaid customer; otherwise only those whose billing day
  // (connectionDate) matches - e.g. picking "2" targets only customers
  // whose package renews/is due on the 2nd of the month.
  const unpaidWithPhone = bulkDayFilter === 'all'
    ? unpaidWithPhoneAll
    : unpaidWithPhoneAll.filter((c) => parseFloat(c.connectionDate) === parseFloat(bulkDayFilter));

  const openBulkModal = () => {
    if (unpaidWithPhoneAll.length === 0) {
      toast.error('No unpaid customers with phone numbers found!');
      return;
    }
    setBulkDayFilter('all');
    const initial = {};
    unpaidWithPhoneAll.forEach((c) => { initial[c.customerId] = true; });
    setBulkSelected(initial);
    setBulkResults([]);
    setBulkOpenedIds({});
    setShowBulkModal(true);
  };

  // Switching the billing-day filter re-selects everyone who now matches it,
  // since the usual flow is "pick a day -> send to everyone on that day".
  // Individual rows can still be unchecked afterwards.
  const handleBulkDayFilterChange = (e) => {
    const value = e.target.value;
    setBulkDayFilter(value);
    const filtered = value === 'all'
      ? unpaidWithPhoneAll
      : unpaidWithPhoneAll.filter((c) => parseFloat(c.connectionDate) === parseFloat(value));
    const next = {};
    filtered.forEach((c) => { next[c.customerId] = true; });
    setBulkSelected(next);
  };

  const toggleBulkSelected = (customerId) => {
    setBulkSelected((prev) => ({ ...prev, [customerId]: !prev[customerId] }));
  };

  const toggleBulkSelectAll = () => {
    const allSelected = unpaidWithPhone.every((c) => bulkSelected[c.customerId]);
    const next = {};
    unpaidWithPhone.forEach((c) => { next[c.customerId] = !allSelected; });
    setBulkSelected(next);
  };

  const selectedCount = unpaidWithPhone.filter((c) => bulkSelected[c.customerId]).length;

  // Opens one customer's pre-filled WhatsApp chat. Used both for the
  // automatic "Send to Selected" pass and as a per-row fallback link, since
  // WhatsApp itself always requires a manual tap on Send inside the chat -
  // there's no way around that from the browser, with or without this app.
  const openWhatsAppLink = (item) => {
    window.open(item.whatsappUrl, '_blank');
    setBulkOpenedIds((prev) => ({ ...prev, [item.customerId]: true }));
  };

  // Same wording as the backend's buildReminderMessage, kept in sync
  // manually - duplicated here (instead of waiting on the API) so every
  // WhatsApp tab can be opened synchronously, in the same click, with
  // nothing awaited in between. That's what keeps the browser's "this was
  // a real click" permission alive for every window.open call below, not
  // just the first one.
  const buildReminderMessageClient = (c) => {
    const duesLine = c.pendingDues > 0 ? ` You also have pending dues of PKR ${c.pendingDues}.` : '';
    return (
      `Dear ${c.name}, this is a reminder that your internet bill of PKR ${c.monthlyFee} is due.${duesLine} Please clear it at your earliest convenience.\n\n` +
      `*💳 Online Payment Options*\n\n` +
      `📱 *JazzCash*\n03000878181\n_Syed Muhammad Bin Haider_\n\n` +
      `🔗 *Raast ID*\n03000878181\n_M. Bin Haider_\n\n` +
      `🏦 *HBL Bank*\n12727900655203\n_M. Bin Haider_\n\n` +
      `⚠️ *Please send a screenshot of the payment after transferring - payment will not be accepted without it.*\n\n` +
      `Thank you.`
    );
  };

  const buildWhatsAppUrl = (c) => {
    let phone = (c.phone || '').replace(/[\s\-\(\)]/g, '');
    if (phone.startsWith('0')) phone = '92' + phone.substring(1);
    if (!phone.startsWith('92') && !phone.startsWith('+')) phone = '92' + phone;
    phone = phone.replace(/\D/g, '');
    return `https://wa.me/${phone}?text=${encodeURIComponent(buildReminderMessageClient(c))}`;
  };

  const sendBulkWhatsApp = () => {
    const ids = Object.keys(bulkSelected).filter((id) => bulkSelected[id]);
    if (ids.length === 0) {
      toast.error('Select at least one customer first!');
      return;
    }
    const selectedCustomers = unpaidWithPhoneAll.filter((c) => ids.includes(c.customerId));

    // Every window.open below fires right here, synchronously, one after
    // another - nothing is awaited first. window.open tells us the truth:
    // it returns the new tab on success, or null/undefined if the browser
    // blocked it as a popup, so we know exactly who actually got opened.
    const opened = {};
    const results = selectedCustomers.map((c) => {
      const whatsappUrl = buildWhatsAppUrl(c);
      const win = window.open(whatsappUrl, '_blank');
      opened[c.customerId] = !!win;
      return {
        name: c.name,
        customerId: c.customerId,
        phone: c.phone,
        monthlyFee: c.monthlyFee,
        pendingDues: c.pendingDues || 0,
        whatsappUrl,
      };
    });
    setBulkResults(results);
    setBulkOpenedIds(opened);

    const openedCount = Object.values(opened).filter(Boolean).length;
    const blockedCount = results.length - openedCount;
    if (blockedCount === 0) {
      toast.success(`Opened WhatsApp for all ${results.length} customer${results.length === 1 ? '' : 's'} at once! Tap Send inside each chat.`);
    } else {
      toast.error(
        `Opened ${openedCount} of ${results.length}. Your browser's popup blocker stopped the rest - tap 📤 Open next to those, ` +
        `or allow pop-ups for this site once (browser menu → Site settings → Pop-ups → Allow) so "Send" opens every chat at once from now on.`
      );
    }

    // Log this bulk action for the activity history - this doesn't need to
    // finish before the chats open, so it isn't awaited above.
    setBulkSending(true);
    API.post('/whatsapp/bulk', {
      customerIds: ids,
      day: bulkDayFilter === 'all' ? undefined : bulkDayFilter,
    }).catch((error) => {
      console.error('Bulk WhatsApp log error:', error);
    }).finally(() => setBulkSending(false));
  };

  const filteredCustomers = customers.filter((c) => {
    const matchesSearch = c.name.toLowerCase().includes(search.toLowerCase()) ||
                          c.customerId.toLowerCase().includes(search.toLowerCase());
    const matchesStatus = filterStatus === 'all' || c.status === filterStatus;
    const matchesPayment = filterPayment === 'all' || c.paymentStatus === filterPayment;
    return matchesSearch && matchesStatus && matchesPayment;
  });

  if (loading) {
    return <div className="loading">Loading customers...</div>;
  }

  return (
    <div className="customers-page">
      <div className="page-header">
        <h2 className="page-title">Customers ({customers.length})</h2>
        <div className="header-buttons">
          <RefreshButton onRefresh={() => loadCustomers(true)} refreshing={refreshing} />
          <button className="btn btn-whatsapp" onClick={openBulkModal}>
            📱 Bulk WhatsApp
          </button>
          <button className="btn btn-primary" onClick={openAddModal}>
            ➕ Add Customer
          </button>
        </div>
      </div>

      <div className="filter-bar">
        <input
          type="text"
          placeholder="Search by name or ID..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="filter-input"
        />
        <select
          value={filterStatus}
          onChange={(e) => setFilterStatus(e.target.value)}
          className="filter-select"
        >
          <option value="all">All Status</option>
          <option value="Active">Active</option>
          <option value="Cut Off">Cut Off</option>
          <option value="Disable">Disable</option>
        </select>
        <select
          value={filterPayment}
          onChange={(e) => setFilterPayment(e.target.value)}
          className="filter-select"
        >
          <option value="all">All Payment</option>
          <option value="Unpaid">Unpaid</option>
          <option value="Paid">Paid</option>
          <option value="1 YEAR ADVANCED">Advanced</option>
          <option value="FREE">FREE</option>
        </select>
      </div>

      <div className="table-container">
        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Customer ID</th>
              <th>Monthly Fee</th>
              <th>Pending Dues</th>
              <th>Day</th>
              <th>Phone</th>
              <th>Status</th>
              <th>Payment</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredCustomers.length === 0 ? (
              <tr><td colSpan="10" className="no-data">No customers found</td></tr>
            ) : (
              filteredCustomers.map((c, index) => (
                <tr key={c._id}>
                  <td>{index + 1}</td>
                  <td><strong>{c.name}</strong></td>
                  <td>{c.customerId}</td>
                  <td>PKR {c.monthlyFee.toLocaleString()}</td>
                  <td className={c.pendingDues > 0 ? 'dues-positive' : 'dues-zero'}>
                    {c.pendingDues > 0 ? `PKR ${c.pendingDues.toLocaleString()}` : '—'}
                  </td>
                  <td className="day-cell">{c.connectionDate || '—'}</td>
                  <td>
                    {c.phone ? (
                      <span className="phone-display">
                        {c.phone}
                        <button
                          className="btn-whatsapp-small"
                          onClick={() => sendWhatsAppReminder(c)}
                          disabled={sendingWhatsApp === c._id}
                          title="Send WhatsApp reminder"
                        >
                          {sendingWhatsApp === c._id ? '⏳' : '📱'}
                        </button>
                      </span>
                    ) : (
                      <span className="no-phone">No phone</span>
                    )}
                  </td>
                  <td>
                    <span className={`status-badge ${c.status.toLowerCase().replace(' ', '-')}`}>
                      {c.status}
                    </span>
                  </td>
                  <td>
                    <span className={`status-badge ${c.paymentStatus.toLowerCase().replace(' ', '-')}`}>
                      {c.paymentStatus}
                    </span>
                  </td>
                  <td>
                    <button className="action-btn" onClick={() => openEditModal(c)}>✏️</button>
                    <button className="action-btn" onClick={() => openHistoryModal(c)} title="View change history">🕘</button>
                    <button className="action-btn delete-btn" onClick={() => handleDelete(c._id)}>🗑️</button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {showModal && (
        <div className="modal-overlay" onClick={() => setShowModal(false)}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <h3>{editingCustomer ? '✏️ Edit Customer' : '➕ Add New Customer'}</h3>
            <form onSubmit={handleSubmit}>
              <div className="modal-grid">
                <div className="form-group">
                  <label>Name *</label>
                  <input type="text" name="name" value={formData.name} onChange={handleInputChange} required />
                </div>
                <div className="form-group">
                  <label>Customer ID *</label>
                  <input type="text" name="customerId" value={formData.customerId} onChange={handleInputChange} required />
                </div>
                <div className="form-group">
                  <label>Monthly Fee (PKR) *</label>
                  <input type="number" name="monthlyFee" value={formData.monthlyFee} onChange={handleInputChange} required />
                </div>
                <div className="form-group">
                  <label>Pending Dues</label>
                  <input type="number" name="pendingDues" value={formData.pendingDues} onChange={handleInputChange} />
                </div>
                <div className="form-group">
                  <label>Day (1-31)</label>
                  <input type="text" name="connectionDate" value={formData.connectionDate} onChange={handleInputChange} placeholder="e.g., 15" />
                </div>
                <div className="form-group">
                  <label>Phone Number</label>
                  <input type="text" name="phone" value={formData.phone} onChange={handleInputChange} placeholder="e.g., 0300-1234567" />
                </div>
                <div className="form-group">
                  <label>Status</label>
                  <select name="status" value={formData.status} onChange={handleInputChange}>
                    <option value="Active">Active</option>
                    <option value="Cut Off">Cut Off</option>
                    <option value="Disable">Disable</option>
                  </select>
                </div>
                <div className="form-group">
                  <label>Payment Status</label>
                  <select name="paymentStatus" value={formData.paymentStatus} onChange={handleInputChange}>
                    <option value="Unpaid">Unpaid</option>
                    <option value="Paid">Paid</option>
                    <option value="1 YEAR ADVANCED">1 YEAR ADVANCED</option>
                    <option value="FREE">FREE</option>
                  </select>
                </div>
              </div>
              <div className="modal-actions">
                <button type="button" className="cancel-btn" onClick={() => setShowModal(false)}>Cancel</button>
                <button type="submit" className="save-btn">{editingCustomer ? 'Update' : 'Add'} Customer</button>
              </div>
            </form>
          </div>
        </div>
      )}

      {showBulkModal && (
        <div className="modal-overlay" onClick={() => setShowBulkModal(false)}>
          <div className="modal bulk-wa-modal" onClick={(e) => e.stopPropagation()}>
            <h3>📱 Bulk WhatsApp Reminders</h3>
            <p className="bulk-wa-hint">
              Only unpaid customers with a phone number are listed. Tapping <strong>"Send to Selected"</strong> opens
              a pre-filled WhatsApp draft for every one of them at once, in one press. If your browser's popup
              blocker stops some of them, allow pop-ups for this site once (browser menu → Site settings → Pop-ups →
              Allow) and every future send will open all of them together. WhatsApp itself still needs a manual tap
              on <strong>Send</strong> inside each chat - that's a WhatsApp rule no app can skip.
            </p>

            <div className="bulk-wa-dayfilter">
              <label htmlFor="bulk-day-filter">Billing day</label>
              <select id="bulk-day-filter" value={bulkDayFilter} onChange={handleBulkDayFilterChange}>
                <option value="all">All days ({unpaidWithPhoneAll.length} unpaid)</option>
                {bulkAvailableDays.map((d) => (
                  <option key={d} value={d}>
                    Day {d} ({bulkDayCounts[d]} unpaid)
                  </option>
                ))}
              </select>
            </div>

            <div className="bulk-wa-selectall">
              <label>
                <input
                  type="checkbox"
                  checked={unpaidWithPhone.length > 0 && unpaidWithPhone.every((c) => bulkSelected[c.customerId])}
                  onChange={toggleBulkSelectAll}
                />
                Select all ({unpaidWithPhone.length})
              </label>
              <span className="bulk-wa-count">{selectedCount} selected</span>
            </div>

            <div className="bulk-wa-list">
              {unpaidWithPhone.length === 0 ? (
                <div className="no-data">No unpaid customers on this billing day.</div>
              ) : (
                unpaidWithPhone.map((c) => {
                const result = bulkResults.find((r) => r.customerId === c.customerId);
                return (
                  <div key={c.customerId} className="bulk-wa-row">
                    <label className="bulk-wa-row-main">
                      <input
                        type="checkbox"
                        checked={!!bulkSelected[c.customerId]}
                        onChange={() => toggleBulkSelected(c.customerId)}
                      />
                      <span className="bulk-wa-row-name">{c.name}</span>
                      <span className="bulk-wa-row-detail">
                        PKR {c.monthlyFee.toLocaleString()}
                        {c.pendingDues > 0 && <span className="dues-positive"> + PKR {c.pendingDues.toLocaleString()} dues</span>}
                      </span>
                    </label>
                    {result && (
                      <button
                        type="button"
                        className="bulk-wa-open-btn"
                        onClick={() => openWhatsAppLink(result)}
                        title="Open this chat again"
                      >
                        {bulkOpenedIds[c.customerId] ? '↻ Reopen' : '📤 Open'}
                      </button>
                    )}
                  </div>
                );
              })
              )}
            </div>

            <div className="modal-actions">
              <button type="button" className="cancel-btn" onClick={() => setShowBulkModal(false)}>Close</button>
              <button type="button" className="save-btn" onClick={sendBulkWhatsApp} disabled={bulkSending || selectedCount === 0}>
                {bulkSending ? 'Opening…' : `Send to Selected (${selectedCount})`}
              </button>
            </div>
          </div>
        </div>
      )}

      {showHistoryModal && (
        <div className="modal-overlay" onClick={() => setShowHistoryModal(false)}>
          <div className="modal history-modal" onClick={(e) => e.stopPropagation()}>
            <h3>🕘 Change History{historyCustomer ? ` - ${historyCustomer.name}` : ''}</h3>
            <p className="bulk-wa-hint">
              Every change to this customer's record - who made it, exactly what changed, and when.
            </p>
            {historyLoading ? (
              <div className="loading">Loading history…</div>
            ) : historyLogs.length === 0 ? (
              <div className="no-data">No recorded changes yet for this customer.</div>
            ) : (
              <div className="bulk-wa-list history-list">
                {historyLogs.map((log) => (
                  <div key={log._id} className="bulk-wa-row history-row">
                    <div className="bulk-wa-row-main" style={{ flexDirection: 'column', alignItems: 'flex-start' }}>
                      <span className="bulk-wa-row-name">
                        {log.action} <span className="no-phone">by {log.user || 'Unknown'}</span>
                      </span>
                      <span className="bulk-wa-row-detail">{log.details}</span>
                      <span className="day-cell">{new Date(log.createdAt).toLocaleString()}</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
            <div className="modal-actions">
              <button type="button" className="cancel-btn" onClick={() => setShowHistoryModal(false)}>Close</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Customers;